In [26]:
# 1D Array 

import numpy as np

marks = np.array([78, 45, 89, 90, 62, 74, 55, 99, 84, 67])

# Calculate the average marks
average_marks=np.mean(marks)
print("Average Marks:", average_marks)

# Calculate the highest marks
highest_marks=np.max(marks)
print("Highest Marks:", highest_marks) 

# Calculate the lowest marks
lowest_marks=np.min(marks)
print("Lowest Marks:", lowest_marks)

# Calculate the total marks
total_marks=np.sum(marks)
print("Total Marks:", total_marks)

# Filtering marks greater than 80
marks_greater_than_80=marks[marks > 80]
print("Marks greater than 80:", marks_greater_than_80)

# Filtering marks less than 60
marks_less_than_60=marks[marks < 60]
print("Marks less than 60:", marks_less_than_60)

# Grace Marks: Add 5 grace marks to all students but should not exceed 100
grace_marks=np.minimum(marks + 5, 100)
print("Marks after adding grace marks (capped at 100):", grace_marks)

# Grade Classification
for mark in marks:
    if mark>=90:
        grade='A'
    elif mark>=80:
        grade='B'
    elif mark>=70:
        grade='C'
    elif mark>60:
        grade='D'
    else:
        grade='F'
    print(f"Mark: {mark}, Grade: {grade}")

attendance = np.array([92, 70, 88, 95, 60, 85, 72, 98, 90, 75])

# Do students with better attendance generally score higher?

print(marks)
print(attendance)

print("Students with higher attendance generally scored better marks.")
print("Student with lower attendance often had lower marks.")

# Make it more professional
# Let's actually FILTER students

high_attendance=attendance>85
print(high_attendance)

print(marks[high_attendance])

# Compare Average
 
print(marks[attendance>85].mean())
print(marks[attendance<=85].mean())

# Which students had both excellent attendance and excellent marks?
print(marks[(attendance>90) & (marks>90)])

# Marks above average
print(marks[marks>average_marks])

# Students with attendance below 75 but marks above 70
print(marks[(attendance<75) & (marks>70)])

# Count how many students scored above 80
count_above_80 = np.sum(marks>80)
print("Number of students who scored above 80:", count_above_80)

Average Marks: 74.3
Highest Marks: 99
Lowest Marks: 45
Total Marks: 743
Marks greater than 80: [89 90 99 84]
Marks less than 60: [45 55]
Marks after adding grace marks (capped at 100): [ 83  50  94  95  67  79  60 100  89  72]
Mark: 78, Grade: C
Mark: 45, Grade: F
Mark: 89, Grade: B
Mark: 90, Grade: A
Mark: 62, Grade: D
Mark: 74, Grade: C
Mark: 55, Grade: F
Mark: 99, Grade: A
Mark: 84, Grade: B
Mark: 67, Grade: D
[78 45 89 90 62 74 55 99 84 67]
[92 70 88 95 60 85 72 98 90 75]
Students with higher attendance generally scored better marks.
Student with lower attendance often had lower marks.
[ True False  True  True False False False  True  True False]
[78 89 90 99 84]
88.0
60.6
[99]
[78 89 90 99 84]
[]
Number of students who scored above 80: 4


In [44]:
# 2D Array

import numpy as np
data = np.array([[78, 92], [45, 70], [89, 88], [90, 95], [62, 60]])

print(data.shape)

print(data[0]) # First row
print(data[1]) # Second row

print(data[0,1]) # Specific value

print(data[:,0]) # Extract Columns
print(data[:,1]) # All attendance

# Statistics on 2D Array
print(data[:,0].mean())
print(data[:,1].mean())

# students with marks above 80 and attendance above 85
condition = (data[:,0]>80) & (data[:,1]>85)
print(data[condition])

# Axis
print(data.sum(axis=0)) # Column wise sum
print(data.sum(axis=1)) # Row wise sum

# New Challenge: Sales Data Analysis

sales = np.array([[200, 220, 250], [150, 180, 210], [300, 310, 330]])
print(sales)

print(sales.sum(axis=1))
print(sales.max())
print(sales.mean())

total_sales = sales.sum(axis=1)

print(total_sales)
print(total_sales.max()) # Which region had the highest total sales?
print(total_sales.argmax()) 

(5, 2)
[78 92]
[45 70]
92
[78 45 89 90 62]
[92 70 88 95 60]
72.8
81.0
[[89 88]
 [90 95]]
[364 405]
[170 115 177 185 122]
[[200 220 250]
 [150 180 210]
 [300 310 330]]
[670 540 940]
330
238.88888888888889
[670 540 940]
940
2
